create table app_user (
  id bigint generated by default as identity,
  birthday bit(255),
  email varchar(255) unique,
  first_name varchar(255),
  last_name varchar(255),
  location varchar(255),
  weight_lbs integer,
  primary key (id)
)
