server:
    port: 55666

logging:
    level:
        com:
            paddlemax:
                api: DEBUG
        org:
            springframework:
                web: DEBUG

security:
    basic:
        enabled: false
