logging:
    path: /log/

spring:
    database:
        driverClassName: org.postgresql.Driver
    datasource:
        password: sK84life!ocrap123
        platform: postgres
        url: jdbc:postgresql://paddlemax.cluster-cnwz9zzm9pih.us-east-1.rds.amazonaws.com:5451/paddlemax
        username: cole

